image: maven:latest

stages:
  - build
  - deploy

build-job:
  stage: build
  script: "mvn verify -B"

deploy-job:
  stage: deploy
  script: echo "deploying..."

deploy-client-job:
  stage: deploy-client
  rules: -if '$CI_COMMIT_REF_NAME == "main"'
  script:
    - (cd ./svelte-rummikub/ ; npm install)
    - (cd ./svelte-rummikub/ ; npm run build)
    - (cd ./svelte-rummikub/ ; npm surge dist)
